// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingMachine.Data.Context;

#nullable disable

namespace VendingMachine.Data.Migrations;

[DbContext(typeof(VendingMachineDbContext))]
[Migration("20250706123036_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

        modelBuilder.Entity("VendingMachine.Models.Coin", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.Property<byte>("Value")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Coins");
            });

        modelBuilder.Entity("VendingMachine.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<byte>("Code")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("Price")
                    .HasColumnType("TEXT");

                b.Property<byte>("Quantity")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Products");
            });
#pragma warning restore 612, 618
    }
}
